openwallet-foundation/credo-ts-ext

.github/workflows/continuous-integration.yml

ci: sign off release please commits

---

packages/redux-store/package.json
packages/redux-store/src/slices/connections/connectionsSlice.ts
packages/redux-store/src/slices/connections/connectionsThunks.ts
packages/redux-store/src/slices/credentials/credentialsSlice.ts
packages/redux-store/src/slices/credentials/credentialsThunks.ts
packages/redux-store/src/slices/proofs/proofsSlice.ts
packages/redux-store/src/slices/proofs/proofsThunks.ts
packages/redux-store/src/types.ts
yarn.lock

refactor(redux-store): use afj delete methods

---

packages/redux-store/package.json
yarn.lock

chore(redux-store): update @aries-framework/core

---

.github/workflows/continuous-integration.yml

ci: trigger on workflow dispatch

---

.prettierignore
package.json

build(prettier): ignore CHANGELOG.md

---

.github/workflows/continuous-integration.yml

ci: add libindy for steps that use yarn

---

README.md
package.json
packages/redux-store/package.json
packages/rest/package.json

Signed-off-by: Berend Sliedrecht <berend@animo.id>

docs: added new rest package to the main readme

---

.github/workflows/continuous-integration.yml

ci: use new signoff option for release-please

---

CONTRIBUTING.md

docs: release process and adding new packages

---

README.md

Signed-off-by: NeilSMyers <mmyersneil@gmail.com>

docs: add react-hooks to main readme

---

packages/rest/src/controllers/credentials/CredentialController.ts
packages/rest/src/controllers/proofs/ProofController.ts
packages/rest/src/schemas/CredentialOfferRequest.ts
packages/rest/src/schemas/CredentialProposalRequest.ts
packages/rest/src/schemas/ProofPresentationRequest.ts
packages/rest/tests/credential.test.ts
packages/rest/tests/proof.test.ts

fixes #57 
Signed-off-by: janrtvld <jan@animo.id[C>

refactor(rest)!: moved connectionId from path to requestbody

---

packages/push-notifications/package.json
packages/react-hooks/package.json
packages/redux-store/package.json
packages/rest/package.json
packages/rest/src/controllers/credentials/CredentialDefinitionController.ts
packages/rest/src/controllers/credentials/SchemaController.ts
packages/rest/tests/credentialDefinition.test.ts
packages/rest/tests/utils/agent.ts
yarn.lock

chore: update afj to latest version

---

packages/rest/src/controllers/proofs/ProofController.ts

#64 
Signed-off-by: janrtvld <jan@animo.id>

refactor(rest)!: changed oob proof parameter from c_i to d_m

---

packages/rest/package.json
packages/rest/src/schemas/InvitationConfigRequest.ts
packages/rest/tests/connection.test.ts

Signed-off-by: janrtvld <jan@animo.id>

feat(rest): added support for custom label and custom imageUrl

---

packages/rest/package.json
yarn.lock

Signed-off-by: janrtvld <jan@animo.id>

chore(rest): updated dependencies

---

packages/rest/README.md
packages/rest/package.json
packages/rest/src/events/ConnectionEvents.ts
packages/rest/src/events/CredentialEvents.ts
packages/rest/src/events/ProofEvents.ts
packages/rest/src/events/WebhookEvent.ts
packages/rest/src/server.ts
packages/rest/src/utils/ServerConfig.ts
packages/rest/tests/utils/webhook.ts
packages/rest/tests/webhook.test.ts
yarn.lock

Closes #63 
Signed-off-by: annelein <anneleinvanreijen@gmail.com>

feat: rest webhooks

---

.github/workflows/continuous-deployment.yml
packages/rest/Dockerfile
packages/rest/README.md
packages/rest/bin/afj-rest.js
packages/rest/docker-compose.yml
packages/rest/package.json
packages/rest/samples/cliConfig.json
packages/rest/samples/sample.ts
packages/rest/samples/sampleWithApp.ts
packages/rest/src/cli.ts
packages/rest/src/cliAgent.ts
packages/rest/src/events/ConnectionEvents.ts
packages/rest/src/events/CredentialEvents.ts
packages/rest/src/events/ProofEvents.ts
packages/rest/src/events/WebhookEvent.ts
packages/rest/src/utils/logger.ts
packages/rest/tests/utils/agent.ts
packages/rest/tests/utils/helpers.ts
yarn.lock

Add CLI to the rest (makes it usable without code) and also adds docker publishing. This means we don't have to set up a boilberplate project every time we use the rest server.

feat(rest): add cli and docker image publishing

---

packages/rest/README.md
packages/rest/src/controllers/basic-messages/BasicMessageController.ts
packages/rest/src/controllers/connections/ConnectionController.ts
packages/rest/src/events/BasicMessageEvents.ts
packages/rest/src/schemas/BasicMessageRequest.ts
packages/rest/src/schemas/ReceiveInvitationByUrlRequest.ts
packages/rest/src/server.ts
packages/rest/tests/basicMessage.test.ts
packages/rest/tests/connection.test.ts
packages/rest/tests/credential.test.ts
packages/rest/tests/credentialDefinition.test.ts
packages/rest/tests/proof.test.ts
packages/rest/tests/schema.test.ts
packages/rest/tests/webhook.test.ts
yarn.lock

- Added functionality to send basic messages
- Added functionality to receive invitation by invitation url

feat(rest): added basic messages and receive invitation by url

---

packages/rest/src/schemas/InvitationConfigRequest.ts
packages/rest/tests/connection.test.ts

Signed-off-by: Jan <60812202+janrtvld@users.noreply.github.com>

feat(rest): added multi use param to create invitation

---

.github/workflows/continuous-integration.yml

Only breaking changes will trigger minor releases now

build: bump feature as patch

---

.github/workflows/continuous-integration.yml
packages/rest/samples/sampleWithApp.ts
packages/rest/src/controllers/credentials/CredentialDefinitionController.ts
packages/rest/src/controllers/credentials/SchemaController.ts
packages/rest/src/schemas/CredentialOfferTemplate.ts
packages/rest/src/schemas/CredentialProposalRequest.ts
packages/rest/src/schemas/ProofProposalRequest.ts
packages/rest/src/schemas/ProofRequestTemplate.ts
packages/rest/src/schemas/ReceiveInvitationRequest.ts
packages/rest/tests/credential.test.ts
packages/rest/tests/utils/webhook.ts
packages/rest/tests/webhook.test.ts
yarn.lock

Improved class validation and cleanup.

feat(rest): improved class validation

---

packages/redux-store/src/recordListener.ts

fix(redux-store): update store listener type

---

packages/redux-store/src/recordListener.ts
packages/redux-store/src/slices/connections/connectionsSelectors.ts
packages/redux-store/src/slices/connections/connectionsSlice.ts
packages/redux-store/src/slices/connections/connectionsThunks.ts
packages/redux-store/src/slices/credentials/credentialsSelectors.ts
packages/redux-store/src/slices/credentials/credentialsSlice.ts
packages/redux-store/src/slices/credentials/credentialsThunks.ts
packages/redux-store/src/slices/mediation/mediationSelectors.ts
packages/redux-store/src/slices/mediation/mediationSlice.ts
packages/redux-store/src/slices/mediation/mediationThunks.ts
packages/redux-store/src/slices/proofs/proofsSelectors.ts
packages/redux-store/src/slices/proofs/proofsThunks.ts
packages/redux-store/tests/index.test.ts

- Minor cleanup for consistency
- Added some unit tests for record event changes
- Fixes an issue where the first record would always be updated

fix(redux-store): tests and proper record update

---

packages/react-hooks/src/ConnectionProvider.tsx
packages/react-hooks/src/CredentialProvider.tsx
packages/react-hooks/src/ProofProvider.tsx

feat(hooks): filter by multiple states with inverse

---

packages/rest/README.md

Signed-off-by: Jim Ezesinachi <jim@animo.id>

docs(rest): removed 'peerDependencies' from README

---

packages/rest/package.json
packages/rest/src/events/BasicMessageEvents.ts
packages/rest/src/events/ConnectionEvents.ts
packages/rest/src/events/CredentialEvents.ts
packages/rest/src/events/ProofEvents.ts
packages/rest/src/events/WebSocketEvents.ts
packages/rest/src/index.ts
packages/rest/src/server.ts
packages/rest/src/utils/ServerConfig.ts
packages/rest/tests/webhook.test.ts
packages/rest/tests/websocket.test.ts
yarn.lock

Signed-off-by: Jim Ezesinachi <jim@animo.id>

feat(rest): added WebSocket event server

---

packages/rest/README.md

Signed-off-by: Jim Ezesinachi <ezesinachijim@gmail.com>

docs: update README

---

packages/react-hooks/src/CredentialProvider.tsx
packages/react-hooks/src/ProofProvider.tsx

added methods that allow to filter credentials and proofs by connection id

feat(react-hooks): filter by connection id

---

.github/workflows/scorecard.yml

Add support for [OpenSSF Scorecard](https://scorecard.dev)

chore: Create scorecard.yml
